//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseCore.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int Id { get; set; }
        public Nullable<int> JobType { get; set; }
        public Nullable<int> PalletId { get; set; }
        public Nullable<int> PositionId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<int> UserCreated { get; set; }
        public Nullable<int> UserCompleted { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
