//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseCore.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pallet
    {
        public int Id { get; set; }
        public int BookingId { get; set; }
        public int PositionId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int Status { get; set; }
        public string POSO { get; set; }
        public string Unit { get; set; }
    }
}
