//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseCore.MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WarehouseEntities : DbContext
    {
        public WarehouseEntities()
            : base("name=WarehouseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Function> Functions { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<POs> POs { get; set; }
    
        public virtual ObjectResult<Admin_User_Result> Admin_User()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Admin_User_Result>("Admin_User");
        }
    
        public virtual ObjectResult<Admin_GetAllFunction_Result> Admin_GetAllFunction()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Admin_GetAllFunction_Result>("Admin_GetAllFunction");
        }
    
        public virtual ObjectResult<WH_GetAllJob_Result> WH_GetAllJob()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WH_GetAllJob_Result>("WH_GetAllJob");
        }
    
        public virtual ObjectResult<WH_GetAllPO_Result> WH_GetAllPO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WH_GetAllPO_Result>("WH_GetAllPO");
        }
    
        public virtual ObjectResult<WH_GetPOByBooking_Result> WH_GetPOByBooking(Nullable<int> bookingid)
        {
            var bookingidParameter = bookingid.HasValue ?
                new ObjectParameter("bookingid", bookingid) :
                new ObjectParameter("bookingid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WH_GetPOByBooking_Result>("WH_GetPOByBooking", bookingidParameter);
        }
    
        public virtual ObjectResult<Admin_GetAllPermission_Result> Admin_GetAllPermission()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Admin_GetAllPermission_Result>("Admin_GetAllPermission");
        }
    
        public virtual ObjectResult<WH_GetAllJob_Result> WH_GetAllJob1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WH_GetAllJob_Result>("WH_GetAllJob1");
        }
    
        public virtual ObjectResult<WH_GetPOById_Result> WH_GetPOById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WH_GetPOById_Result>("WH_GetPOById", idParameter);
        }
    
        public virtual ObjectResult<WH_GetPOById_Result> WH_GetPOById1(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WH_GetPOById_Result>("WH_GetPOById1", idParameter);
        }
    
        public virtual ObjectResult<WH_GetPOById_Result> WH_GetPOById2(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WH_GetPOById_Result>("WH_GetPOById2", idParameter);
        }
    }
}
